# Generated by Django 3.1.2 on 2020-10-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IG', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
    ]
